### ISSUE TITLE
Procedure to create conda package allennlp v0.8

### ISSUE THREAD

**Issue by test9723497834565** [conda-forge/allennlp-feedstock#2]
Hi,

I would like to install version 0.8 with conda but this version is not currently available on https://anaconda.org/conda-forge/allennlp

Do you know which step I would have to follow to create the conda package?
Alternatively, could you provide the package?

I've tried to do "conda skeleton pypi allennlp" but there was an error in my ubuntu on Windows.

Thank you very much.

**Comment by sodre** [comment]
We are working on getting 0.8.0 available. It was not possible because pytorch 1.0.0 was not in conda-forge or defaults until very recently.

**Comment by test9723497834565** [comment]
Thank you.
